sources:
  - name: airstats
    schema: RAW
    tables:
      - name: airports
        identifier: airports
      - name: comments
        identifier: airport_comments
      - name: runways
        identifier: runways